from PySide6.QtWidgets import QWidget, QVBoxLayout, QLabel, QTabWidget, QListWidget, QListWidgetItem, QPushButton, QHBoxLayout

class PluginsView(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 24, 24, 24)
        layout.setSpacing(8)
        title = QLabel("Plugins")
        title.setStyleSheet("font-size: 20px; font-weight: 600;")
        layout.addWidget(title)
        tabs = QTabWidget()
        self.installed_list = QListWidget()
        self.market_list = QListWidget()
        tabs.addTab(self.installed_list, "Installed")
        tabs.addTab(self.market_list, "Marketplace")
        layout.addWidget(tabs)
        footer = QHBoxLayout()
        refresh_btn = QPushButton("Refresh")
        footer.addStretch(1)
        footer.addWidget(refresh_btn)
        layout.addLayout(footer)
        item = QListWidgetItem("No plugins installed")
        self.installed_list.addItem(item)
        item2 = QListWidgetItem("Marketplace not connected")
        self.market_list.addItem(item2)
